/**
 * @file ble-wasm.h
 * @brief Bluetooth Configuration. Services' UUID, MTU, etc.
 * @author O. Nakakaze
 */

#define GATTS_TAG "BLE-Module"

#define GATTS_SERVICE_UUID_WASM   0x00FF
#define GATTS_CHAR_UUID_WASM      0xFF01
#define GATTS_DESCR_UUID_WASM     0x3333
#define GATTS_NUM_HANDLE_WASM     4

#define GATTS_SERVICE_UUID_MESH_GRAPH   0x00EE
#define GATTS_CHAR_UUID_MESH_GRAPH      0xEE01
#define GATTS_DESCR_UUID_MESH_GRAPH     0x2222
#define GATTS_NUM_HANDLE_MESH_GRAPH     4

#define TEST_DEVICE_NAME            "ESP_WASM_READER"
#define TEST_MANUFACTURER_DATA_LEN  17

#define GATTS_DEMO_CHAR_VAL_LEN_MAX 0x40

#define PREPARE_BUF_MAX_SIZE 1024

#define PROFILE_NUM 2
#define PROFILE_WASM_APP_ID 0
#define PROFILE_MESH_GRAPH_APP_ID 1

#define BLE_LOCAL_MTU 500
#define BLE_ROUTE_TABLE_MTU 100

#define BLE_ADD_DATA_DEST 0x03
#define BLE_REMOVE_DATA_DEST 0x04
#define BLE_WASM_MOVING 0x05
#define BLE_WASM_OFF_MSG 0x06